### ISSUE TITLE
Still compatible with current version of Redux-Saga?

### ISSUE THREAD

**Issue by markerikson** [threepointone/react-redux-saga#1]
I'm still very much a newbie with Redux-Saga, but know that it's gone through some API changes over the last few months.  I see that this library was written about six months ago.  Do any of the Redux-Saga API changes affect this library, or should it still be able to work as-is?

**Comment by threepointone** [comment]
I think it's changed, I'll have a look later today

**Comment by m-shulipa** [comment]
@markerikson 
Using this lib with `redux-saga`, everything is working fine! 😉

**Comment by markerikson** [comment]
Cool, thanks.  I'll close this, then.
